name: Generate Profile Cards

on:
  schedule:
    - cron: "0 0 * * *" # daily
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate overview card
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: sajithmym
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Colombo
          filename: assets/metrics-overview.svg

      - name: Generate languages card
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: sajithmym
          template: classic
          base: metadata
          config_timezone: Asia/Colombo
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          filename: assets/metrics-languages.svg

      - name: Generate achievements card
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: sajithmym
          template: classic
          base: metadata
          config_timezone: Asia/Colombo
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_display: compact
          filename: assets/metrics-achievements.svg
